spring:
  profiles:
    active: local  # Профиль по умолчанию
  config:
    import:
      - classpath:application-${spring.profiles.active}.yml
      - classpath:application-user.yml
      - classpath:application-user-${spring.profiles.active}.yml
      - classpath:application-storage.yml
      - classpath:application-storage-${spring.profiles.active}.yml