spring:
  profiles:
    active: local
  config:
    import:
      - classpath:application-${spring.profiles.active}.yml
      - classpath:application-user.yml
      - classpath:application-user-${spring.profiles.active}.yml
      - classpath:application-storage.yml
      - classpath:application-storage-${spring.profiles.active}.yml
      - classpath:application-product.yml
      - classpath:application-product-${spring.profiles.active}.yml
      - classpath:application-order.yml
      - classpath:application-order-${spring.profiles.active}.yml
      - classpath:application-payment.yml
      - classpath:application-payment-${spring.profiles.active}.yml
      - classpath:application-security.yml
      - classpath:application-notification.properties